### ISSUE TITLE
Publish 🚀 

### ISSUE THREAD

**Issue by cngJo** [jop-software/doctrine-uuid-generators#1]
**Tasks**
- [X] Set LICENSE (MIT)
- [x] Documentation
- [x] Set Repository to public
- [x] Setup deployment to packagist
- [x] Version 1.0.0 release

**Comment by cngJo** [comment]
🚀 🎉
